apiVersion: v1
kind: ConfigMap
metadata: 
  name: env-config
data:
  POSTGRES_HOST: owoh-db.c5lrhgdarmiu.us-east-1.rds.amazonaws.com
  POSTGRES_DB: postgres
  AWS_BUCKET: project-owoh-dev
  AWS_REGION: us-east-1
  AWS_PROFILE: nodeuser
  JWT_SECRET: testing
  URL: http://localhost:8100 